### ISSUE TITLE
Crash when trying to add a task at 00:00

### ISSUE THREAD

**Issue by postcanonical** [Medvedev91/timetome#34] opened 2024-04-24 11:39 UTC
Steps to reproduce:
1. Go to History
2. Click edit
3. Click add button
4. Set time to 00:00 this day
5. Close History
7. Try to open Summary
8. Crash

Platform: Android 14, F-droid repo

**Comment by Medvedev91** [comment] 2024-04-24 12:01
What version of the app? You can find it at the bottom of the settings sheet. Like v2024.04.21.515-base.

**Comment by postcanonical** [comment] 2024-04-24 16:16
v2024.04.18.500-fdroid

**Comment by Medvedev91** [comment] 2024-04-24 16:29
> v2024.04.18.500-fdroid

I can't reproduce this crash. It was #21 a few versions ago, but it has been fixed.

**Comment by Medvedev91** [comment] 2024-04-24 16:33
> v2024.04.18.500-fdroid

Wow, I think I've found the reason. Will be fixed in the next version.

**Comment by postcanonical** [comment] 2024-04-24 16:36
> Wow, I think I've found the reason. Will be fixed in the next version.

Great! thanks!

**Comment by Medvedev91** [comment] 2024-05-10 18:27
Please check out the v2024.05.01.522. Already in all the stores.

**Closed** 2024-05-11 13:41 UTC
